pipeline {
  agent any

  stages {

    stage('Build') {
      script {
        // if pull request isn't from IQSS, CHANGE_FORK only provides org/user
        if (env.CHANGE_FORK) {
          env.PR_REPO = "https://github.com/" + env.CHANGE_FORK + "/dataverse"
        } else {
          env.PR_REPO = env.GIT_URL
        }
      }
      steps {
	// clean plate
        sh 'rm -rf target/*'
        // do work
        sh './tests/jenkins/podman/run_test_suite.bash -r ${PR_REPO} -b ${CHANGE_BRANCH}'
      }
    }

    stage('Post') {
      steps {
	junit 'target/surefire-reports/*.xml'
	step(
	  [$class: 'JacocoPublisher', 
	  execPattern: 'target/*.exec',
	  classPattern: 'target/classes',
	  sourcePattern: 'src/main/java',
	  exclusionPattern: 'src/test*']
	)
        script {
          if (fileExists('./ansible_complete')) {
            sh '/bin/rm ./ansible_complete'
          } else {
            error('Ansible run terminated abnormally, failing build.')
          }
        }
      }
    }
  }
}
