pipeline {
  agent any

  stages {

    stage('Build') {
      when {
	changeset "doc/sphinx-guides/**"
      }
      steps {
	sh 'cd ${WORKSPACE}/doc/sphinx-guides/'
	sh 'make clean'
	sh 'make html'
	sh 'make epub'
      }
    }

    stage('Test') {
      when {
	changeset "doc/sphinx-guides/**"
      }
      steps {
	sh 'cd ${WORKSPACE}/doc/sphinx-guides/'
	sh 'make doctest'
      }
    }

    stage('Post') {
      when {
	changeset "doc/sphinx-guides/**"
      }
      steps {
	sh 'cd ${WORKSPACE}/doc/sphinx-guides/'
	sh 'cp build/epub/Dataverse.epub build/html'
	sh 'zip -r ${WORKSPACE}/${CHANGE_BRANCH}.zip ./'
      }
    }
  }
}
