pipeline {
  agent any

  stages {

    stage('Build') {
      steps {
	sh 'cd doc/sphinx-guides/ && make clean'
	sh 'cd doc/sphinx-guides/ && make html'
	sh 'cd doc/sphinx-guides/ && make epub'
      }
    }

    stage('Test') {
      steps {
      }
    }

    stage('Post') {
      steps {
	sh 'cd doc/sphinx-guides/ && cp build/epub/Dataverse.epub build/html'
	sh 'cd doc/sphinx-guides/ && zip -r ${WORKSPACE}/${CHANGE_BRANCH}.zip ./'
      }
    }
  }
}
